version = 1
name = 'adaptive'
remote = true
dirty = false
license = 'Apache-2.0'
status = 'clean'

[[sources]]
url = 'https://github.com/android/skills/tree/main/jetpack-compose/adaptive'
ref = 'main'
path = 'jetpack-compose/adaptive'
